kind: ConfigMap
apiVersion: v1
metadata:
  name: deisio-caddyfile
data:
  Caddyfile: |-
    :2015{{ if ne .Values.hostname "" }}, {{ .Values.hostname }}{{ end }} {
      root /svc
      gzip {
        not /healthz /assets/img
      }
      minify /assets/css
      minify /assets/js{{ if ne .Values.tls.key "" }}
      tls /etc/tls/cert.pem /etc/tls/key.pem{{ else if not .Values.tls.letsencrypt }}
      tls off{{ end }}
      status 200 /healthz
    }